// Promote an explicitly evaluated, frozen checkpoint into the source snapshot.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),write=require('./atomic-write.cjs');
const root=path.resolve(__dirname,'..'),dir=path.resolve(process.argv[2]||'runs/falling_release'),out=path.join(root,'site-data');
const read=file=>JSON.parse(fs.readFileSync(path.join(dir,file))),checkpoint=read('checkpoint.json'),evaluation=read('evaluation.json'),replay=read('replay.json');
if(evaluation.status!=='complete'||evaluation.pairs.length!==24||replay.rules!=='falling-v1')throw Error('Complete paired evaluation and falling replay are required.');
const modelFile=path.join(dir,'input/model.json'),inputModel=JSON.parse(fs.readFileSync(modelFile));
const hash=raw=>crypto.createHash('sha256').update(raw).digest('hex');
if(hash(fs.readFileSync(path.join(root,'flytris/web/versus-core.js')))!==checkpoint.manifest.hashes['versus-core.js']||hash(fs.readFileSync(path.join(root,'flytris/web/falling-policy.cjs')))!==checkpoint.manifest.hashes['falling-policy.cjs'])throw Error('Site physics/planner differ from the evaluated snapshot.');
if(hash(fs.readFileSync(modelFile))!==checkpoint.manifest.hashes['model.json'])throw Error('Starting model differs from the evaluated snapshot.');
const model={...inputModel,weights:checkpoint.weights,task:'falling-v1',training_seed:71,generation:checkpoint.generation,controller:{tickMs:50,planner:'bounded-reachable-v1',physicsSha256:checkpoint.manifest.hashes['versus-core.js'],plannerSha256:checkpoint.manifest.hashes['falling-policy.cjs']}};
model.metadata={...model.metadata,model_sha256:hash(JSON.stringify({model,rulesVersion:2}))};
const mean=a=>a.reduce((n,v)=>n+v,0)/a.length,s=evaluation.summary;
const results={task:'falling-v1',modelId:model.metadata.model_sha256,generation:checkpoint.generation,trainingSeconds:checkpoint.trainingSeconds,trainingStatus:checkpoint.trainingStatus,interruption:'Windows denied an atomic checkpoint rename; the six-hour budget was not completed.',evaluatedAt:evaluation.completedAt,summary:s,baselineValidation:mean(checkpoint.baselineValidation.map(r=>r.lines)),bestValidation:mean(checkpoint.bestValidation.map(r=>r.lines)),pairs:evaluation.pairs};
const hours=(checkpoint.trainingSeconds/3600).toFixed(2),ci=s.paired95CI.map(n=>n.toFixed(1)).join(' to '),gain=(100*(s.afterMean/s.beforeMean-1)).toFixed(1);
const rows=[800,500,250].map((ms,i)=>{const pairs=evaluation.pairs.filter(p=>p.after.gravityMs===ms);return {name:['Easy','Medium','Hard'][i],before:mean(pairs.map(p=>p.before.lines)).toFixed(1),after:mean(pairs.map(p=>p.after.lines)).toFixed(1)};});
const text=`# Falling-rules checkpoint evaluation\n\nCheckpoint after ${checkpoint.generation} generations and ${hours} hours of training. The planned six-hour run stopped early when Windows denied a checkpoint rename. Its saved best validation weights were frozen, then evaluated separately.\n\nFresh test mean: **${s.beforeMean.toFixed(1)} → ${s.afterMean.toFixed(1)} lines/game** (+${gain}% on this test set). Paired mean gain: ${s.pairedGain.toFixed(1)} lines, 95% bootstrap interval **${ci}**. The interval includes zero: this small evaluation does not establish a reliable general improvement. Some seeds regress.\n\n24 paired games represent eight independent piece sequences, each repeated at three speeds. The interval resamples seed clusters, not 24 independent games. Tests did not select weights. Games have a three-minute simulated clock; hard drop is allowed. Both baseline and trained weights use the same falling controller.\n\n| Gravity | Before | After |\n|---|---:|---:|\n${rows.map(r=>`| ${r.name} | ${r.before} | ${r.after} |`).join('\n')}\n\nValidation mean: ${results.baselineValidation.toFixed(1)} → ${results.bestValidation.toFixed(1)} lines/game. Validation selected the checkpoint and is not an independent test.\n\nThe replay uses the first predeclared test seed at medium gravity (7000000), not the highest score. It replays recorded controls through the actual falling engine. The live opponent computes new routes in a browser worker, with both match clocks paused during planning.\n\nModel ID: ${results.modelId}. Evaluated: ${evaluation.completedAt}.\n\nThe historical placement trial, raw-feature baseline and random baseline are preserved separately in REPORT.md and results.json. They are not directly comparable to this timed falling experiment. The fixed circuit and route planner do not learn; only eight readout weights do.\n`;
const html=`<section class="card falling-results" aria-label="Current falling-rules model"><div class="section-eyebrow">CURRENT PLAYER / FALLING RULES</div><h2>A new player at the controls.</h2><div class="stats"><div><strong>${s.beforeMean.toFixed(1)}</strong><small>Before · test lines/game</small></div><div><strong>${s.afterMean.toFixed(1)}</strong><small>Saved checkpoint · test lines/game</small></div><div><strong>+${gain}%</strong><small>Mean change on this test set</small></div></div><p>${hours} hours trained · ${checkpoint.generation} generations.</p><p><strong>Mixed evidence:</strong> 24 paired games across eight independent sequences. Mean gain ${s.pairedGain.toFixed(1)} lines; 95% interval ${ci}. Some sequences regress, and the interval includes zero.</p><p>The replay and live opponent now use falling ticks, midair rotations and legal slides. Replay: first test seed at medium gravity.</p></section>`;
write(path.join(out,'versus-model.json'),model);write(path.join(out,'falling-results.json'),results);write(path.join(out,'falling-replay.json'),replay);write(path.join(out,'FALLING_RESULTS.md'),text);write(path.join(out,'falling-summary.html'),html);
console.log(`Integrated evaluated checkpoint ${results.modelId}, ${s.afterMean.toFixed(1)} test lines/game.`);
